#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGStories.h"
#import "SWGTopStories.h"


@protocol SWGLastNews
@end

@interface SWGLastNews : SWGObject


@property(nonatomic) NSArray<SWGStories>* stories;

@property(nonatomic) NSArray<SWGTopStories>* topStories;

@end
