#import <Foundation/Foundation.h>
#import "SWGLastNews.h"
#import "SWGError.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGNewslatestApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGNewslatestApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGNewslatestApi*) sharedAPI;
///
///
/// 最新消息
/// 获取最新消息
///
/// 
///
/// @return SWGLastNews*
-(NSNumber*) newsLatestGetWithCompletionHandler: 
    (void (^)(SWGLastNews* output, NSError* error)) handler;



@end
