#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGOtherObj
@end

@interface SWGOtherObj : SWGObject


@property(nonatomic) NSString* color;

@property(nonatomic) NSString* thumbnail;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* name;

@end
