#import <Foundation/Foundation.h>
#import "SWGStartImage.h"
#import "SWGError.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGStartimageApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGStartimageApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGStartimageApi*) sharedAPI;
///
///
/// 启动界面图像获取
/// start-image 后为图像分辨率，接受如下格式\n- 格式: 320\*432 480\*728 720\*1184 1080\*1776
///
/// 
///
/// @return SWGStartImage*
-(NSNumber*) startImage10801776GetWithCompletionHandler: 
    (void (^)(SWGStartImage* output, NSError* error)) handler;



@end
