#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGStartImage
@end

@interface SWGStartImage : SWGObject

/* 供显示的图片版权信息 [optional]
 */
@property(nonatomic) NSString* text;
/* 图像的 URL [optional]
 */
@property(nonatomic) NSString* img;

@end
