#import <Foundation/Foundation.h>
#import "SWGError.h"
#import "SWGThemes.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGThemesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGThemesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGThemesApi*) sharedAPI;
///
///
/// 主题查看
/// 主题日报列表查看
///
/// 
///
/// @return SWGThemes*
-(NSNumber*) themesGetWithCompletionHandler: 
    (void (^)(SWGThemes* output, NSError* error)) handler;



@end
