#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTopStories
@end

@interface SWGTopStories : SWGObject

/* 新闻标题 [optional]
 */
@property(nonatomic) NSString* title;
/* 图片 [optional]
 */
@property(nonatomic) NSString* image;
/* 供 Google Analytics 使用 [optional]
 */
@property(nonatomic) NSString* gaPrefix;
/* 作用未知 [optional]
 */
@property(nonatomic) NSString* type;
/* url 与 share_url 中最后的数字（应为内容的 id） [optional]
 */
@property(nonatomic) NSNumber* _id;

@end
