#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGOtherObj.h"
#import "SWGSubscribed.h"


@protocol SWGThemes
@end

@interface SWGThemes : SWGObject


@property(nonatomic) NSNumber* limit;

@property(nonatomic) NSArray<SWGSubscribed>* subscribed;

@property(nonatomic) NSArray<SWGOtherObj>* others;

@end
